// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CadenceUnit } from "./CadenceUnit";

export type Cadence = { amount: number, unit: CadenceUnit, };
