// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `PUT /api/completions/{id}`.
 */
export type CompletionInput = { task_id: number, executor_id: number, 
/**
 * UTC unix milliseconds.
 */
completed_at: number, };
