// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Completion = { 
/**
 * Client-generated UUIDv7.
 */
id: string, task_id: number, executor_id: number, 
/**
 * UTC unix milliseconds.
 */
completed_at: number, };
