// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent on `GET /api/events` (as SSE `data`). Events carry no payload: clients refetch.
 */
export type Event = { "type": "changed", project: number | null, };
