// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupColor } from "./GroupColor";

/**
 * Body for creating or updating a group. Updates replace both fields, so an omitted
 * `color` clears it.
 */
export type GroupInput = { name: string, color?: GroupColor | null, };
