// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for creating or renaming a group.
 */
export type GroupInput = { name: string, };
