// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Solarized accent, named like the palette variables in the UI.
 */
export type GroupColor = "yellow" | "orange" | "red" | "magenta" | "violet" | "blue" | "cyan" | "green";
