// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Group } from "./Group";
import type { Project } from "./Project";
import type { TaskView } from "./TaskView";

/**
 * A project with its groups, sorted by name, and its tasks, sorted so the ones needing
 * attention come first.
 */
export type ProjectView = { project: Project, groups: Array<Group>, tasks: Array<TaskView>, };
