// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { TaskView } from "./TaskView";

/**
 * A project with its tasks, sorted so the ones needing attention come first.
 */
export type ProjectView = { project: Project, tasks: Array<TaskView>, };
