// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";

/**
 * Body for creating or updating a task.
 */
export type TaskInput = { name: string, cadence: Cadence, priority: number, };
