// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";

export type Task = { id: number, name: string, cadence: Cadence, 
/**
 * 0-5, where 5 is the highest priority.
 */
priority: number, };
