// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";
import type { Completion } from "./Completion";

export type TaskView = { 
/**
 * `null` if the task has never been completed.
 */
last_completion: Completion | null, 
/**
 * The calendar day (`YYYY-MM-DD`, family time zone) the task is due again.
 * `null` if the task has never been completed, which means it is due now.
 */
due: string | null, 
/**
 * Days since the last completion divided by the cadence in days.
 * `null` if the task has never been completed.
 */
urgency: number | null, 
/**
 * Due today or earlier (`urgency >= 1`, or never completed).
 */
overdue: boolean, id: number, name: string, cadence: Cadence, 
/**
 * 0-5, where 5 is the highest priority.
 */
priority: number, };
